# Iván Álvarez García DNI: 49623492A
OPTS = -Wall -Wextra -O3 -std=c++0x

all: mcp_greedy

mcp_greedy: mcp_greedy.cc
	g++ ${OPTS} -o mcp_greedy mcp_greedy.cc	 

tar: mcp_greedy.cc makefile
	tar cvfz 49623492A.tar.gz mcp_greedy.cc makefile


 