# Iván Álvarez García DNI: 49623492A
OPTS = -Wall -Wextra -O3 -std=c++0x

all: mcp:bt

maze: mcp_bt.cc
	g++ ${OPTS} -o mcp_bt mcp_bt.cc	 

tar: mcp_bt.cc makefile
	tar cvfz 49623492A.tar.gz mcp_bt.cc makefile


 