# Iván Álvarez García DNI: 49623492A
OPTS = -Wall -Wextra -O3 -std=c++0x

all: mcp_bb

maze: mcp_bb.cc
	g++ ${OPTS} -o mcp_bb mcp_bb.cc	 

tar: mcp_bb.cc makefile
	tar cvfz 49623492A.tar.gz mcp_bb.cc makefile


 